// Validates and cleans the harvested tier-1 spec snapshots.
//
// Oracle's specs are Swagger 2.0 documents generated by different teams over
// a decade - expect variance. This script, per catalogued spec:
//   1. parses the snapshot (provider-dev/downloaded/<index_key>.yaml)
//   2. applies deterministic per-service fixes (rules in PRE_FIXES below,
//      never hand-edits), recording every fix applied
//   3. converts Swagger 2.0 -> OpenAPI 3.0 (swagger2openapi, patch mode -
//      patches applied by the converter are part of the fix report)
//   4. validates the result with @apidevtools/swagger-parser
//   5. writes provider-dev/downloaded/cleaned/<index_key>.json and the
//      per-spec fix report provider-dev/config/spec_clean_report.json
//
// All outputs are held in memory and written only if every spec passes:
// validate-and-fail-without-writing. Deterministic and re-runnable.
//
// Usage: node provider-dev/scripts/clean_specs.mjs [--only key1,key2]

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import SwaggerParser from '@apidevtools/swagger-parser';
import s2o from 'swagger2openapi';
import {
  CLEANED_DIR,
  CONFIG_DIR,
  DOWNLOADED_DIR,
  loadCatalog
} from './lib/catalog.mjs';

const REPORT_PATH = path.join(CONFIG_DIR, 'spec_clean_report.json');

// Deterministic per-service fixes, keyed by catalog index_key. Each rule is a
// named function doc -> array of fix strings (empty if nothing to do).
// Rules are added here as validation surfaces problems; never edit snapshots.
const PRE_FIXES = {
  '*': [
    // Swagger 2.0 requires a version string; some OCI specs carry numbers
    function infoVersionString(doc) {
      if (doc.info && typeof doc.info.version === 'number') {
        doc.info.version = String(doc.info.version);
        return ['info.version coerced to string'];
      }
      return [];
    },
    // strip vendor x-obmcs-* extensions that carry no generator meaning but
    // occasionally hold non-conformant values
    function stripTopLevelUnknowns(doc) {
      const fixes = [];
      for (const k of Object.keys(doc)) {
        if (k.startsWith('x-obmcs')) {
          delete doc[k];
          fixes.push(`top-level ${k} removed`);
        }
      }
      return fixes;
    }
  ]
};

function applyPreFixes(indexKey, doc) {
  const applied = [];
  for (const rule of [...(PRE_FIXES['*'] || []), ...(PRE_FIXES[indexKey] || [])]) {
    applied.push(...rule(doc));
  }
  return applied;
}

async function main() {
  const args = process.argv.slice(2);
  const onlyIdx = args.indexOf('--only');
  const only = onlyIdx !== -1 ? new Set(args[onlyIdx + 1].split(',')) : null;

  const catalog = loadCatalog().filter((e) => e.tier === '1');
  const targets = only ? catalog.filter((e) => only.has(e.index_key)) : catalog;
  if (targets.length === 0) {
    console.error('Error: no catalogued tier-1 specs matched');
    process.exit(1);
  }

  const outputs = [];
  const report = {};
  const errors = [];

  for (const entry of targets) {
    const specPath = path.join(DOWNLOADED_DIR, entry.local_file);
    const label = entry.index_key;
    if (!fs.existsSync(specPath)) {
      errors.push(`${label}: snapshot missing (${specPath}) - run bin/fetch-specs.sh`);
      continue;
    }
    process.stdout.write(`cleaning ${label} ... `);
    try {
      const doc = yaml.load(fs.readFileSync(specPath, 'utf8'));
      const fixes = applyPreFixes(entry.index_key, doc);

      // Swagger 2.0 -> OAS 3.0. patch:true applies minor spec repairs and
      // records them; warnOnly surfaces non-fatal issues in the report.
      const converted = await s2o.convertObj(doc, {
        patch: true,
        warnOnly: true,
        anchors: true,
        direct: false
      });
      const oas = converted.openapi;
      const patches = (converted.options?.patches || 0);
      const warnings = (converted.options?.warnings || []).map((w) => String(w.message || w));

      // validate a structured clone - SwaggerParser.validate dereferences in place
      await SwaggerParser.validate(structuredClone(oas));

      const opCount = Object.values(oas.paths || {})
        .flatMap((p) => Object.keys(p))
        .filter((v) => ['get', 'post', 'put', 'patch', 'delete', 'head'].includes(v)).length;

      outputs.push({
        file: path.join(CLEANED_DIR, `${entry.index_key}.json`),
        content: JSON.stringify(oas, null, 2)
      });
      report[label] = {
        service: entry.service,
        status: 'valid',
        operations: opCount,
        pre_fixes: fixes,
        converter_patches: patches,
        converter_warnings: warnings
      };
      console.log(`ok (${opCount} operations, ${fixes.length} fixes, ${patches} converter patches, ${warnings.length} warnings)`);
    } catch (err) {
      console.log('FAILED');
      errors.push(`${label}: ${err.message.split('\n')[0]}`);
      report[label] = { service: entry.service, status: 'invalid', error: err.message.split('\n').slice(0, 5).join('\n') };
    }
  }

  if (errors.length > 0) {
    console.error(`\nValidation failed - nothing written (${errors.length} error(s)):`);
    for (const e of errors) console.error(`  - ${e}`);
    process.exit(1);
  }

  fs.mkdirSync(CLEANED_DIR, { recursive: true });
  for (const out of outputs) {
    fs.writeFileSync(out.file, out.content);
  }
  // merge with prior report so --only runs do not drop other entries
  let existing = {};
  if (fs.existsSync(REPORT_PATH)) {
    existing = JSON.parse(fs.readFileSync(REPORT_PATH, 'utf8'));
  }
  const merged = { ...existing, ...report };
  const sorted = Object.fromEntries(Object.keys(merged).sort().map((k) => [k, merged[k]]));
  fs.writeFileSync(REPORT_PATH, JSON.stringify(sorted, null, 2) + '\n');

  console.log(`\nCleaned ${outputs.length} spec(s) -> ${CLEANED_DIR}`);
  console.log(`Fix report: ${REPORT_PATH}`);
}

main().catch((err) => {
  console.error('Error cleaning specs:', err);
  process.exit(1);
});
